import { GradeLevel } from '../types';

export interface BrainTeaser {
  id: string;
  gradeLevel: GradeLevel;
  subject: 'math' | 'science' | 'wordplay' | 'logic' | 'nature' | 'riddle';
  subjectLabel: string;
  subjectIcon: string;
  question: string;
  options: string[];
  correctAnswerIndex: number;
  hint: string;
  thinkingAngle?: string;
  funFactExplanation: string;
}

export const BRAIN_TEASERS_CATALOG: BrainTeaser[] = [
  // ==========================================
  // KINDERGARTEN & PRE-K (Ages 4-6)
  // ==========================================
  {
    id: 'k-1',
    gradeLevel: 'kindergarten',
    subject: 'math',
    subjectLabel: 'Counting & Combining',
    subjectIcon: '🍎',
    question: 'You have 3 red apples in your basket. Mom gives you 2 more apples. How many apples do you have altogether?',
    options: ['4 apples', '5 apples', '6 apples', '3 apples'],
    correctAnswerIndex: 1,
    hint: 'Try counting up: start from 3 and count forward two more hops on your fingers.',
    thinkingAngle: 'Counting Forward: Instead of starting over from 1, hold the first group in your mind and count on!',
    funFactExplanation: 'Awesome math! 3 + 2 = 5 apples. Apples float in water because a quarter of their volume is actually air!',
  },
  {
    id: 'k-2',
    gradeLevel: 'kindergarten',
    subject: 'nature',
    subjectLabel: 'Animal Kingdom',
    subjectIcon: '🐾',
    question: 'What do we call a baby dog?',
    options: ['A Kitten', 'A Calf', 'A Puppy', 'A Chick'],
    correctAnswerIndex: 2,
    hint: 'Think of the playful little pet with floppy ears that loves to wag its tail and bark softly.',
    thinkingAngle: 'Animal Families: Different animals have special names for their young (a cat has a kitten, a cow has a calf).',
    funFactExplanation: 'Spot on! A baby dog is called a puppy. Puppies are born without teeth and sleep up to 18 hours a day as they grow!',
  },
  {
    id: 'k-3',
    gradeLevel: 'kindergarten',
    subject: 'riddle',
    subjectLabel: 'Fruit Detective',
    subjectIcon: '🍌',
    question: 'I have a bright yellow coat that you peel off before you eat my sweet fruit. What am I?',
    options: ['A Banana', 'An Orange', 'A Lemon', 'A Watermelon'],
    correctAnswerIndex: 0,
    hint: 'Notice the shape and color: which fruit is long and curved, and grown in bunches hanging high in trees?',
    thinkingAngle: 'Feature Matching: Combine all the clues (yellow + curved + peelable + sweet) to narrow down the choices.',
    funFactExplanation: 'Clever sleuthing! Bananas grow pointing upwards toward the sky, which gives them their famous gentle curve!',
  },
  {
    id: 'k-4',
    gradeLevel: 'kindergarten',
    subject: 'science',
    subjectLabel: 'Color Chemistry',
    subjectIcon: '🎨',
    question: 'What color do you create when you mix sunny Yellow and sky Blue paint together?',
    options: ['Purple', 'Green', 'Orange', 'Pink'],
    correctAnswerIndex: 1,
    hint: 'Think of the natural color of tree leaves, frogs, and freshly cut grass.',
    thinkingAngle: 'Primary to Secondary: When two primary colors merge, they blend their light wavelengths into a brand-new hue.',
    funFactExplanation: 'Brilliant! Yellow and Blue make Green! Red, Yellow, and Blue are the 3 primary colors that can mix into nearly every color on Earth.',
  },
  {
    id: 'k-5',
    gradeLevel: 'kindergarten',
    subject: 'wordplay',
    subjectLabel: 'Sound Rhymes',
    subjectIcon: '🎵',
    question: 'Which of these words rhymes with the word "CAT"?',
    options: ['DOG', 'HAT', 'FISH', 'BIRD'],
    correctAnswerIndex: 1,
    hint: 'Say the words out loud: listen closely to the sound at the very end of "c-AT".',
    thinkingAngle: 'Sound Isolation: Focus purely on the ending sound (-at) rather than what the objects look like.',
    funFactExplanation: 'Great ear! "Cat" and "Hat" share the exact same ending sound. Rhyming teaches your brain to recognize word families when reading!',
  },
  {
    id: 'k-6',
    gradeLevel: 'kindergarten',
    subject: 'logic',
    subjectLabel: 'Shape Geometry',
    subjectIcon: '🔺',
    question: 'How many straight sides does a triangle have?',
    options: ['2 sides', '3 sides', '4 sides', '5 sides'],
    correctAnswerIndex: 1,
    hint: 'Think about the prefix "tri-", like the three wheels on a tricycle.',
    thinkingAngle: 'Root Word Logic: Look for clues inside the name itself to unlock the mathematical property.',
    funFactExplanation: 'Super job! A triangle always has 3 straight sides and 3 corners. Triangles are the strongest structural shape in architecture and bridges!',
  },
  {
    id: 'k-7',
    gradeLevel: 'kindergarten',
    subject: 'nature',
    subjectLabel: 'Ocean Wonders',
    subjectIcon: '🐟',
    question: 'Which animal breathes underwater using gills and swims with fins, but cannot walk on land?',
    options: ['A Fish', 'A Duck', 'A Frog', 'A Dog'],
    correctAnswerIndex: 0,
    hint: 'Rule out animals that can walk around in your backyard or waddle along a pond shore.',
    thinkingAngle: 'Elimination of Extremes: Consider which animal would be completely unable to breathe or move outside of water.',
    funFactExplanation: 'Fantastic! Fish use special organs called gills to take oxygen directly out of the water while swimming with their fins!',
  },
  {
    id: 'k-8',
    gradeLevel: 'kindergarten',
    subject: 'logic',
    subjectLabel: 'Pattern Recognition',
    subjectIcon: '🔴',
    question: 'Look at this color pattern: Red, Blue, Red, Blue, Red, ___? What comes next?',
    options: ['Yellow', 'Blue', 'Green', 'Purple'],
    correctAnswerIndex: 1,
    hint: 'Sing the pattern like a musical beat and listen to which color takes the alternating turn.',
    thinkingAngle: 'Alternating Loops: Look for the rule that repeats over and over in an AB pattern.',
    funFactExplanation: 'You got it! The pattern alternates Red then Blue. Pattern recognition is one of the foundations of computer programming and math!',
  },
  {
    id: 'k-9',
    gradeLevel: 'kindergarten',
    subject: 'science',
    subjectLabel: 'Day & Night Sky',
    subjectIcon: '☀️',
    question: 'What giant glowing ball in the daytime sky gives our planet light and warmth?',
    options: ['The Moon', 'The Sun', 'A Cloud', 'A Rainbow'],
    correctAnswerIndex: 1,
    hint: 'Think about which object rises to make daytime and sets in the evening so stars can appear.',
    thinkingAngle: 'Source vs Reflector: While the moon shines softly at night, what creates the actual daytime heat and illumination?',
    funFactExplanation: 'Spectacular! The Sun is actually a giant star over 93 million miles away! It provides the energy that powers all plant and animal life on Earth.',
  },
  {
    id: 'k-10',
    gradeLevel: 'kindergarten',
    subject: 'riddle',
    subjectLabel: 'Outside The Box Riddle',
    subjectIcon: '🪑',
    question: 'I have four legs and a flat wooden back to hold your plates, but I have no feet and cannot walk. What am I?',
    options: ['A Horse', 'A Table', 'A Dog', 'A Bicycle'],
    correctAnswerIndex: 1,
    hint: 'Look around your dining room or kitchen: think about furniture that stands on support posts.',
    thinkingAngle: 'Literal vs Figurative: Words like "legs" can describe parts of furniture as well as living bodies!',
    funFactExplanation: 'Sharp deduction! A table has legs for support, but it is furniture, not an animal! Lateral thinking means looking past first impressions.',
  },
  {
    id: 'k-11',
    gradeLevel: 'kindergarten',
    subject: 'science',
    subjectLabel: 'Melting Magic',
    subjectIcon: '🍦',
    question: 'What happens to a cold ice pop if you leave it on the kitchen counter on a sunny day?',
    options: ['It turns into a solid rock', 'It melts into a sweet liquid puddle', 'It flies up into the sky', 'It catches on fire'],
    correctAnswerIndex: 1,
    hint: 'Think about what happens to snow or ice cubes when they warm up.',
    thinkingAngle: 'States of Matter: When frozen things absorb heat from the air, their solid structure loosens.',
    funFactExplanation: 'Spot on! Heat causes solid ice to melt into liquid. If you freeze that puddle back in the freezer, it turns solid again!',
  },
  {
    id: 'k-12',
    gradeLevel: 'kindergarten',
    subject: 'nature',
    subjectLabel: 'Farm Animals',
    subjectIcon: '🐮',
    question: 'Which farm animal says "Moo" and gives us fresh milk to drink?',
    options: ['A Horse', 'A Pig', 'A Cow', 'A Sheep'],
    correctAnswerIndex: 2,
    hint: 'Think of the big gentle animal that chews grass in the meadow and wears a bell.',
    thinkingAngle: 'Characteristic Association: Pair the distinctive animal vocalization with what product comes from it.',
    funFactExplanation: 'Super job! Cows spend around 8 hours a day chewing grass and cud, and have four stomach compartments to digest all that fiber!',
  },

  // ==========================================
  // 1ST GRADE (Ages 6-7)
  // ==========================================
  {
    id: 'g1-1',
    gradeLevel: '1st_grade',
    subject: 'math',
    subjectLabel: 'Ten-Frame Reasoning',
    subjectIcon: '⭐',
    question: 'You have collected 7 golden stars. How many more stars do you need to complete a full set of 10?',
    options: ['2 stars', '3 stars', '4 stars', '5 stars'],
    correctAnswerIndex: 1,
    hint: 'Picture a ten-frame with 7 boxes filled in. How many empty boxes remain in the grid?',
    thinkingAngle: 'Complements of Ten: Grouping numbers up to 10 is one of the most powerful mental shortcuts in mathematics.',
    funFactExplanation: 'Bingo! 7 + 3 = 10. Number bonds of 10 make fast mental math easy for the rest of your life!',
  },
  {
    id: 'g1-2',
    gradeLevel: '1st_grade',
    subject: 'science',
    subjectLabel: 'Prism Weather',
    subjectIcon: '🌈',
    question: 'What two weather ingredients must be present in the sky at the exact same time to create a rainbow?',
    options: ['Snow and Heavy Wind', 'Sunlight and Water Droplets', 'Thunder and Darkness', 'Hail and Thick Fog'],
    correctAnswerIndex: 1,
    hint: 'Think about what shines and what gets sprayed in the air when you hold a garden hose on a sunny afternoon.',
    thinkingAngle: 'Dual Conditions: A phenomenon often requires both an energy source and a reflective medium together.',
    funFactExplanation: 'Spectacular! When bright sunlight shines through falling raindrops, each drop acts like a tiny glass prism that bends and separates light into 7 colors!',
  },
  {
    id: 'g1-3',
    gradeLevel: '1st_grade',
    subject: 'riddle',
    subjectLabel: 'Clock Riddle',
    subjectIcon: '⏰',
    question: 'What has a round face and two moving hands, but has no arms, legs, or eyes?',
    options: ['A Clock', 'A Teddy Bear', 'A Mirror', 'A Robot'],
    correctAnswerIndex: 0,
    hint: 'Think about something ticking on the wall that tells people when it is time for breakfast or bed.',
    thinkingAngle: 'Double Meanings: Everyday objects often borrow anatomical words (like "face" or "hands") for their dials and pointers.',
    funFactExplanation: 'Clever thinking! An analog clock has an hour hand and a minute hand, and its flat numbered front is called its face!',
  },
  {
    id: 'g1-4',
    gradeLevel: '1st_grade',
    subject: 'nature',
    subjectLabel: 'Insect Anatomy',
    subjectIcon: '🐝',
    question: 'How many legs does a true adult insect, such as an ant or a honeybee, always have?',
    options: ['4 legs', '6 legs', '8 legs', '10 legs'],
    correctAnswerIndex: 1,
    hint: 'Spiders have 8 legs, but true insects belong to a different family that has one fewer pair.',
    thinkingAngle: 'Taxonomy Traits: Insects always have 3 body segments (head, thorax, abdomen) with exactly one pair of legs per segment.',
    funFactExplanation: 'Spot on! All insects have exactly 6 legs (3 pairs). Spiders are arachnids, not insects, because they have 8 legs and 2 body segments!',
  },
  {
    id: 'g1-5',
    gradeLevel: '1st_grade',
    subject: 'math',
    subjectLabel: 'Analog Time Sense',
    subjectIcon: '🕒',
    question: 'If the short hand of a clock points right at 4 and the long hand points straight up at 12, what time is it?',
    options: ['12:00', '4:00', '4:30', '1:00'],
    correctAnswerIndex: 1,
    hint: 'Remember which hand tells the hour (short hand) and what straight up at 12 means for the minutes.',
    thinkingAngle: 'Functional Division: Each clock hand carries a distinct role—the slow hand tracks hours, the fast hand tracks minutes.',
    funFactExplanation: 'Outstanding! That is 4:00 (four o’clock). The short hand is the hour hand, and pointing directly at 12 marks zero minutes past the hour.',
  },
  {
    id: 'g1-6',
    gradeLevel: '1st_grade',
    subject: 'wordplay',
    subjectLabel: 'Antonym Opposites',
    subjectIcon: '❄️',
    question: 'Which of these words is the true OPPOSITE (antonym) of the word "HOT"?',
    options: ['Warm', 'Sunny', 'Cold', 'Bright'],
    correctAnswerIndex: 2,
    hint: 'Think about how ice cubes feel compared to a steaming bowl of soup.',
    thinkingAngle: 'Spectrum Extremes: Opposites live at the opposite ends of a measurement scale (hot vs cold, high vs low).',
    funFactExplanation: 'Exact! "Cold" is the true antonym of "Hot". Antonyms are word pairs with completely contrary meanings.',
  },
  {
    id: 'g1-7',
    gradeLevel: '1st_grade',
    subject: 'logic',
    subjectLabel: 'Outside The Box Coins',
    subjectIcon: '🪙',
    question: 'You have two US coins in your pocket that add up to 15 cents. One of them is NOT a nickel. What are the two coins?',
    options: ['Two Dimes', 'A Dime and a Nickel', 'Three Nickels', 'A Quarter and a Penny'],
    correctAnswerIndex: 1,
    hint: 'Read the wording carefully: ONE coin is not a nickel... but what about the OTHER coin?',
    thinkingAngle: 'Question Assumption Audit: The riddle says "one of them" is not a nickel—it never said BOTH aren\'t nickels!',
    funFactExplanation: 'Brain buster cracked! One is a dime (which is not a nickel), and the other one IS a nickel! 10¢ + 5¢ = 15¢. Lateral thinking checks every word!',
  },
  {
    id: 'g1-8',
    gradeLevel: '1st_grade',
    subject: 'nature',
    subjectLabel: 'Metamorphosis',
    subjectIcon: '🐸',
    question: 'Which animal starts its life swimming in a pond as a gill-breathing tadpole before growing legs to hop on land?',
    options: ['A Frog', 'A Turtle', 'A Goldfish', 'A Lizard'],
    correctAnswerIndex: 0,
    hint: 'Listen along marshy pond edges: this green hopper catches bugs with a lightning-fast sticky tongue.',
    thinkingAngle: 'Life Cycle Transformation: Look for the amphibian that undergoes a dramatic body transformation called metamorphosis.',
    funFactExplanation: 'Spectacular! Frogs are amphibians. Tadpoles hatch in water, develop lungs and legs, absorb their tails, and emerge onto land as frogs!',
  },
  {
    id: 'g1-9',
    gradeLevel: '1st_grade',
    subject: 'math',
    subjectLabel: 'Savings Math',
    subjectIcon: '🎯',
    question: 'A toy plane at the store costs 8 stars. You currently have 5 stars saved. How many more stars must you earn?',
    options: ['2 stars', '3 stars', '4 stars', '5 stars'],
    correctAnswerIndex: 1,
    hint: 'Think about the gap between where you are (5) and where you want to be (8). Count the steps between them.',
    thinkingAngle: 'Difference as Distance: Subtraction is simply measuring the distance between two points on a number line.',
    funFactExplanation: 'Spot on! 8 - 5 = 3 stars needed. Setting financial savings goals helps people of all ages achieve what they dream of!',
  },
  {
    id: 'g1-10',
    gradeLevel: '1st_grade',
    subject: 'riddle',
    subjectLabel: 'Digger’s Riddle',
    subjectIcon: '🕳️',
    question: 'What gets bigger and bigger the more material you take away from it?',
    options: ['A Pile of Sand', 'A Hole in the ground', 'A Box of Toys', 'A Backpack'],
    correctAnswerIndex: 1,
    hint: 'Think about digging at the beach with a bucket and plastic shovel. What happens to the opening as you scoop away dirt?',
    thinkingAngle: 'Inversion Thinking: Usually removing things makes an object smaller. What object is defined by the absence of matter?',
    funFactExplanation: 'Genius! A hole grows larger every time you scoop out more dirt! Puzzles like this exercise our ability to view negative space.',
  },
  {
    id: 'g1-11',
    gradeLevel: '1st_grade',
    subject: 'science',
    subjectLabel: 'Shadow Science',
    subjectIcon: '👤',
    question: 'What happens to your shadow on the playground when the Sun is directly overhead at noon compared to early morning?',
    options: ['It becomes much longer', 'It disappears into the sky', 'It becomes much shorter right under your feet', 'It turns into bright colors'],
    correctAnswerIndex: 2,
    hint: 'Think about where the sunlight is coming from: if the light shines straight down from above, where does the blockage fall?',
    thinkingAngle: 'Light Angle Projection: Low light sources cast long, stretched shadows, while overhead light sources cast compact shadows.',
    funFactExplanation: 'Terrific observation! At noon, the Sun is at its highest point, so your body blocks light directly downward, casting a tiny, short shadow!',
  },
  {
    id: 'g1-12',
    gradeLevel: '1st_grade',
    subject: 'wordplay',
    subjectLabel: 'Compound Words',
    subjectIcon: '🌻',
    question: 'When you combine the word "SUN" and the word "FLOWER", what kind of living thing do you get?',
    options: ['A Tree', 'A Sunflower', 'A Daisy', 'A Cactus'],
    correctAnswerIndex: 1,
    hint: 'Combine the two words directly into a single word without adding or removing any letters.',
    thinkingAngle: 'Lexical Building Blocks: Compound words join two independent words together to name something that shares their qualities.',
    funFactExplanation: 'Awesome! A sunflower is a tall plant with a bright yellow bloom that actually turns its head to follow the path of the Sun across the sky!',
  },

  // ==========================================
  // 2ND GRADE (Ages 7-8)
  // ==========================================
  {
    id: 'g2-1',
    gradeLevel: '2nd_grade',
    subject: 'math',
    subjectLabel: 'Currency Computation',
    subjectIcon: '🪙',
    question: 'If you have 2 quarters, 1 dime, and 1 nickel, how much total money do you have?',
    options: ['50 cents', '60 cents', '65 cents', '75 cents'],
    correctAnswerIndex: 2,
    hint: 'Group your coins by value: two quarters make half a dollar (50¢). Now add the ten-cent piece and five-cent piece.',
    thinkingAngle: 'Chunking Strategies: Combine familiar large denominations first before adding smaller units.',
    funFactExplanation: 'Terrific! 25¢ + 25¢ = 50¢; 50¢ + 10¢ = 60¢; 60¢ + 5¢ = 65¢. Quarters have 119 ridges along their edges, originally made to stop people from shaving off silver!',
  },
  {
    id: 'g2-2',
    gradeLevel: '2nd_grade',
    subject: 'science',
    subjectLabel: 'Arctic Adaptations',
    subjectIcon: '🐻‍❄️',
    question: 'Underneath their thick white fur, what color is a polar bear’s actual skin?',
    options: ['Snow White', 'Pink', 'Jet Black', 'Bright Blue'],
    correctAnswerIndex: 2,
    hint: 'Think about which color absorbs the most heat and warmth from the Sun in freezing Arctic winds.',
    thinkingAngle: 'Thermodynamics in Nature: Light colors reflect radiation, while dark surfaces absorb solar heat to keep animals warm.',
    funFactExplanation: 'Mind-blowing adaptation! A polar bear’s skin is pitch black to absorb maximum warmth from the Sun! Their fur is actually transparent and hollow, reflecting light so it appears white.',
  },
  {
    id: 'g2-3',
    gradeLevel: '2nd_grade',
    subject: 'logic',
    subjectLabel: 'Sequence Progression',
    subjectIcon: '🔢',
    question: 'Look at the sequence: 4, 8, 12, 16, 20, ___? What number belongs in the blank space?',
    options: ['22', '24', '26', '28'],
    correctAnswerIndex: 1,
    hint: 'Notice the constant leap from each number to the next: how much are you adding each time?',
    thinkingAngle: 'Constant Intervals: Identify the common difference between adjacent terms to predict future values.',
    funFactExplanation: 'You nailed it! The sequence adds 4 each step (+4). Counting by 4s is also the multiplication table of 4 (4 × 6 = 24)!',
  },
  {
    id: 'g2-4',
    gradeLevel: '2nd_grade',
    subject: 'riddle',
    subjectLabel: 'Rainy Day Riddle',
    subjectIcon: '☂️',
    question: 'What goes up when rain comes pouring down?',
    options: ['An Airplane', 'An Umbrella', 'The Temperature', 'A Kite'],
    correctAnswerIndex: 1,
    hint: 'Think about what you open and push upwards above your head to prevent yourself from getting soaked.',
    thinkingAngle: 'Opposite Directional Motion: Look for an everyday tool whose deployment direction contrasts with falling precipitation.',
    funFactExplanation: 'Ha! An umbrella goes up when the rain comes down! Umbrellas were invented over 4,000 years ago, originally used in ancient Egypt to create shade from the hot sun.',
  },
  {
    id: 'g2-5',
    gradeLevel: '2nd_grade',
    subject: 'nature',
    subjectLabel: 'Oceanic Wanderers',
    subjectIcon: '🐧',
    question: 'Which bird has wings that act like underwater flippers, allowing it to "fly" through freezing oceans, but cannot fly in the air?',
    options: ['An Eagle', 'A Penguin', 'A Seagull', 'A Pelican'],
    correctAnswerIndex: 1,
    hint: 'Think of the waddling bird dressed in a natural black-and-white tuxedo living in the southern hemisphere.',
    thinkingAngle: 'Evolutionary Tradeoffs: Denser bones make airborne flight impossible, but allow deep, agile swimming underwater.',
    funFactExplanation: 'Spot on! Emperor penguins can dive more than 1,700 feet deep and hold their breath for over 20 minutes while chasing fish through icy seas!',
  },
  {
    id: 'g2-6',
    gradeLevel: '2nd_grade',
    subject: 'science',
    subjectLabel: 'Thermal Physics',
    subjectIcon: '🧊',
    question: 'At what temperature on the Fahrenheit scale does liquid water freeze into solid ice?',
    options: ['0°F', '32°F', '50°F', '100°F'],
    correctAnswerIndex: 1,
    hint: 'On the Celsius scale it freezes at 0°, but on the Fahrenheit scale used in US weather, the freezing mark is higher.',
    thinkingAngle: 'Standard Reference Points: Scientific scales use physical phase changes (freezing and boiling) as anchor points.',
    funFactExplanation: 'Spot on! Water freezes at 32°F (0°C). Water is one of the only substances on Earth that expands when it freezes, which is why ice cubes float!',
  },
  {
    id: 'g2-7',
    gradeLevel: '2nd_grade',
    subject: 'logic',
    subjectLabel: 'Family Deduction',
    subjectIcon: '👨‍👩‍👧‍👦',
    question: 'Emma has 4 sisters. Each of her 4 sisters has exactly 1 brother. How many brothers does Emma have?',
    options: ['4 brothers', '1 brother', '5 brothers', '0 brothers'],
    correctAnswerIndex: 1,
    hint: 'Think about the entire family together: does each sister have a DIFFERENT brother, or do they all share the same boy?',
    thinkingAngle: 'Shared Relationships: Avoid multiplying relationships when a single entity can hold the exact same connection to multiple people.',
    funFactExplanation: 'Clever deduction! There is only 1 brother in the whole family! He is the brother to Emma and to every single one of her sisters.',
  },
  {
    id: 'g2-8',
    gradeLevel: '2nd_grade',
    subject: 'math',
    subjectLabel: 'Equal Grouping',
    subjectIcon: '🧁',
    question: 'A baker bakes 24 fresh muffins and packs them into boxes of 6. How many full boxes can the baker pack?',
    options: ['3 boxes', '4 boxes', '5 boxes', '6 boxes'],
    correctAnswerIndex: 1,
    hint: 'Think of division as repeated subtraction or skip counting by 6: 6, 12, 18...',
    thinkingAngle: 'Equal Partitioning: How many groups of size 6 can be created from a total pool of 24?',
    funFactExplanation: 'Outstanding! 24 ÷ 6 = 4 boxes. Multiplication and division are inverse operations (4 × 6 = 24)!',
  },
  {
    id: 'g2-9',
    gradeLevel: '2nd_grade',
    subject: 'riddle',
    subjectLabel: 'Morning Vanity Riddle',
    subjectIcon: '🪮',
    question: 'I have many teeth, but I cannot bite, chew, or eat any food. What am I?',
    options: ['A Shark', 'A Comb', 'A Saw', 'A Zipper'],
    correctAnswerIndex: 1,
    hint: 'Look in your bathroom drawer: what tool do you slide through tangled hair to make it neat?',
    thinkingAngle: 'Metaphorical Anatomy: Many everyday manufactured tools use biological names ("teeth", "lips", "arms") for their functional parts.',
    funFactExplanation: 'Sharp thinking! A hair comb has teeth to separate and smooth hair strands without ever taking a bite!',
  },
  {
    id: 'g2-10',
    gradeLevel: '2nd_grade',
    subject: 'science',
    subjectLabel: 'Respiration Chemistry',
    subjectIcon: '🫁',
    question: 'Which gas in the air do human beings and animals inhale to give their muscles and cells energy to live?',
    options: ['Helium', 'Oxygen', 'Carbon Dioxide', 'Argon'],
    correctAnswerIndex: 1,
    hint: 'Plants release this fresh gas during daylight, and our lungs absorb it with every breath we take.',
    thinkingAngle: 'Biological Reciprocity: Animals inhale what plants produce, and plants absorb the carbon dioxide that animals breathe out.',
    funFactExplanation: 'Terrific! Oxygen makes up about 21% of our atmosphere. Your red blood cells carry oxygen molecules from your lungs to every cell in your body!',
  },
  {
    id: 'g2-11',
    gradeLevel: '2nd_grade',
    subject: 'wordplay',
    subjectLabel: 'Homophone Clues',
    subjectIcon: '👂',
    question: 'Which pair of words sound IDENTICAL when spoken aloud, but have different meanings and spellings?',
    options: ['Cat / Hat', 'Sea / See', 'Run / Walk', 'Sun / Star'],
    correctAnswerIndex: 1,
    hint: 'One is a vast body of saltwater, and the other is what you do with your eyes.',
    thinkingAngle: 'Homophone Discrimination: English words can share pronunciation while having completely different origins and orthography.',
    funFactExplanation: 'Great linguistic ear! "Sea" (the ocean) and "See" (vision) are homophones. Knowing homophones helps you master spelling in writing!',
  },
  {
    id: 'g2-12',
    gradeLevel: '2nd_grade',
    subject: 'math',
    subjectLabel: 'Odd vs Even Logic',
    subjectIcon: '⚖️',
    question: 'If you add any two ODD numbers together (such as 3 + 5 or 7 + 1), the sum will ALWAYS be what kind of number?',
    options: ['An Odd Number', 'An Even Number', 'A Negative Number', 'Zero'],
    correctAnswerIndex: 1,
    hint: 'Every odd number has one "leftover" unpaired unit. What happens when you combine two leftover units together?',
    thinkingAngle: 'Parity Pairing: Odd numbers are pairs with one remainder. Combining two odd numbers pairs up both remainders!',
    funFactExplanation: 'Brilliant logic! Odd + Odd always equals Even! (3 + 5 = 8, 7 + 9 = 16). Understanding parity properties helps mathematicians check their work quickly.',
  },

  // ==========================================
  // 3RD GRADE (Ages 8-9)
  // ==========================================
  {
    id: 'g3-1',
    gradeLevel: '3rd_grade',
    subject: 'math',
    subjectLabel: 'Multiplication Strategies',
    subjectIcon: '🍕',
    question: 'A pizza chef cuts 6 pizzas into 8 equal slices each. How many total slices are ready to serve?',
    options: ['42 slices', '46 slices', '48 slices', '54 slices'],
    correctAnswerIndex: 2,
    hint: 'Try doubling: 8 doubled is 16. What is three groups of 16?',
    thinkingAngle: 'Decomposition: Break complex products into familiar components (6 × 8 = (5 × 8) + 8 = 40 + 8).',
    funFactExplanation: 'Outstanding! 6 × 8 = 48 slices. A fun rhyme to remember: "Six times eight fell on the floor, picked it up, it was forty-eight!"',
  },
  {
    id: 'g3-2',
    gradeLevel: '3rd_grade',
    subject: 'science',
    subjectLabel: 'Planetary Science',
    subjectIcon: '🪐',
    question: 'Which planet in our solar system is famous for its massive, visible rings composed of billions of chunks of ice and rock?',
    options: ['Mars', 'Jupiter', 'Saturn', 'Neptune'],
    correctAnswerIndex: 2,
    hint: 'It is the sixth planet from the Sun, situated between giant Jupiter and icy Uranus.',
    thinkingAngle: 'Astronomical Identification: While all gas giants have faint rings, one planet has wide, brilliant rings reflecting sunlight.',
    funFactExplanation: 'Magnificent! Saturn’s majestic rings span up to 175,000 miles across, yet in many places they are only about 30 feet thick!',
  },
  {
    id: 'g3-3',
    gradeLevel: '3rd_grade',
    subject: 'logic',
    subjectLabel: 'Transitive Reasoning',
    subjectIcon: '🕵️',
    question: 'Maya is taller than Leo. Leo is taller than Sam. Which of the following statements MUST be true?',
    options: ['Sam is taller than Maya', 'Maya is taller than Sam', 'Sam and Maya are the same height', 'Leo is the tallest'],
    correctAnswerIndex: 1,
    hint: 'Line them up in your mind from tallest to shortest based on the clues: Maya > Leo > Sam.',
    thinkingAngle: 'The Transitive Property: If A > B and B > C, then logically A must always be greater than C.',
    funFactExplanation: 'Sharp deductive reasoning! Since Maya is taller than Leo, and Leo is taller than Sam, Maya must be taller than Sam. This is the mathematical Transitive Property!',
  },
  {
    id: 'g3-4',
    gradeLevel: '3rd_grade',
    subject: 'math',
    subjectLabel: 'Fraction Magnitude',
    subjectIcon: '🥧',
    question: 'Which of these fractions represents the LARGEST portion of a pie: 1/2, 1/4, or 1/8?',
    options: ['1/8 of a pie', '1/4 of a pie', '1/2 of a pie', 'They are all equal'],
    correctAnswerIndex: 2,
    hint: 'Imagine slicing a pie: do you get a bigger slice if you divide the pie between 2 people or between 8 people?',
    thinkingAngle: 'Inverse Denominator Rule: As the denominator increases, the whole is partitioned into smaller and smaller slices.',
    funFactExplanation: 'Spot on! 1/2 is half of the entire pie! With unit fractions (numerator = 1), smaller denominators mean fewer, but much larger, pieces.',
  },
  {
    id: 'g3-5',
    gradeLevel: '3rd_grade',
    subject: 'science',
    subjectLabel: 'Plant Biology',
    subjectIcon: '🌿',
    question: 'What is the biological process where green leaves capture sunlight, carbon dioxide, and water to synthesize glucose food?',
    options: ['Photosynthesis', 'Metamorphosis', 'Hibernation', 'Evaporation'],
    correctAnswerIndex: 0,
    hint: 'Break down the Greek roots: "photo-" means light, and "synthesis" means putting components together.',
    thinkingAngle: 'Etymology Clues: Scientific terms almost always describe their mechanism through their Greek and Latin roots.',
    funFactExplanation: 'Phenomenal! Photosynthesis allows plants to produce energy while releasing fresh oxygen into the air for all humans and animals to breathe!',
  },
  {
    id: 'g3-6',
    gradeLevel: '3rd_grade',
    subject: 'riddle',
    subjectLabel: 'Kitchen Riddle',
    subjectIcon: '🧽',
    question: 'What household object is full of holes, yet can still absorb and hold a large amount of water?',
    options: ['A Net', 'A Sponge', 'A Colander', 'A Sieve'],
    correctAnswerIndex: 1,
    hint: 'Think about what you use to wipe down clean kitchen counters or wash dishes.',
    thinkingAngle: 'Apparent Paradox: Holes usually let liquid drain out, unless microscopic pockets create capillary action that traps water.',
    funFactExplanation: 'You nailed it! A sponge is full of porous air pockets that trap and hold water through surface tension and capillary action!',
  },
  {
    id: 'g3-7',
    gradeLevel: '3rd_grade',
    subject: 'logic',
    subjectLabel: 'Lateral Thinking Race',
    subjectIcon: '🏃',
    question: 'You are competing in a footrace and you sprint past the runner who is currently in 2nd place. What place are you in now?',
    options: ['1st place', '2nd place', '3rd place', 'You won the race'],
    correctAnswerIndex: 1,
    hint: 'Be careful! You passed the person who was in 2nd place—did you pass the person leading the race in 1st?',
    thinkingAngle: 'Positional Substitution: Taking over someone\'s position puts you into THEIR former rank, not the rank ahead of them.',
    funFactExplanation: 'Classic brain teaser! You took 2nd place! The person who was in 1st place is still in front of you. To take 1st, you have to pass 1st!',
  },
  {
    id: 'g3-8',
    gradeLevel: '3rd_grade',
    subject: 'math',
    subjectLabel: 'Geometric Perimeter',
    subjectIcon: '📐',
    question: 'A square sandbox has sides that each measure 5 feet long. What is the total PERIMETER of the sandbox?',
    options: ['10 feet', '15 feet', '20 feet', '25 feet'],
    correctAnswerIndex: 2,
    hint: 'Perimeter is the distance all the way around the outer boundary: add all 4 equal sides together.',
    thinkingAngle: 'Perimeter vs Area: Perimeter measures the linear border fence (5 + 5 + 5 + 5), while area measures the flat square tiles inside (5 × 5).',
    funFactExplanation: 'Spot on! 5 + 5 + 5 + 5 = 20 feet (or 4 × 5 = 20 ft). Perimeter comes from the Greek words "peri" (around) and "metron" (measure).',
  },
  {
    id: 'g3-9',
    gradeLevel: '3rd_grade',
    subject: 'science',
    subjectLabel: 'Hydrologic Cycle',
    subjectIcon: '💧',
    question: 'When warm sunbeams heat up a puddle on the sidewalk, causing liquid water to turn into invisible water vapor in the air, what is this called?',
    options: ['Precipitation', 'Evaporation', 'Condensation', 'Freezing'],
    correctAnswerIndex: 1,
    hint: 'Look at the root of the word: the liquid is turning into "vapor".',
    thinkingAngle: 'Phase Shifts: The water cycle relies on continuous phase changes: evaporation (liquid to gas), condensation (gas to liquid), and precipitation.',
    funFactExplanation: 'Terrific! Evaporation lifts water molecules into the atmosphere, where they later cool and condense into clouds that produce rain!',
  },
  {
    id: 'g3-10',
    gradeLevel: '3rd_grade',
    subject: 'wordplay',
    subjectLabel: 'Mirror Palindromes',
    subjectIcon: '🔁',
    question: 'Which of these words is a true PALINDROME—spelled the exact same forwards and backwards?',
    options: ['ROCKET', 'RACECAR', 'BICYCLE', 'AIRPLANE'],
    correctAnswerIndex: 1,
    hint: 'Test each word by reading it in reverse from the last letter to the first letter.',
    thinkingAngle: 'Symmetry in Language: Palindromic words have an axis of symmetry right down their middle letter.',
    funFactExplanation: 'Brilliant! R-A-C-E-C-A-R spelled in reverse is still R-A-C-E-C-A-R! Other famous palindromes include "level", "radar", and "kayak".',
  },
  {
    id: 'g3-11',
    gradeLevel: '3rd_grade',
    subject: 'nature',
    subjectLabel: 'Ecosystem Partners',
    subjectIcon: '🌺',
    question: 'When honeybees and butterflies visit flowers to drink sweet nectar, what crucial job do they perform for the ecosystem?',
    options: ['They build tree nests', 'They pollinate flowers so seeds and fruit can grow', 'They frighten away garden birds', 'They create garden soil'],
    correctAnswerIndex: 1,
    hint: 'They carry microscopic golden grains from flower to flower on their fuzzy bodies.',
    thinkingAngle: 'Symbiosis: Both organisms benefit—the insect gets sugar fuel, and the plant achieves cross-fertilization.',
    funFactExplanation: 'Spectacular! Pollinators are responsible for 1 out of every 3 bites of food humans eat, including apples, berries, and nuts!',
  },
  {
    id: 'g3-12',
    gradeLevel: '3rd_grade',
    subject: 'logic',
    subjectLabel: 'Letter Play Paradox',
    subjectIcon: '7️⃣',
    question: 'I am an odd number. If you take away just ONE letter from my written name, I become EVEN. What number am I?',
    options: ['NINE', 'SEVEN', 'ELEVEN', 'THREE'],
    correctAnswerIndex: 1,
    hint: 'Look closely at the letters in the spelling of each number name: what happens if you remove the first letter of S-E-V-E-N?',
    thinkingAngle: 'Word Transformation: Switch from mathematical calculations to spelling mechanics to spot the hidden word inside.',
    funFactExplanation: 'Masterful lateral thinking! Remove the letter "S" from the word "SEVEN", and you are left with the word "EVEN"! Puzzles like this teach flexibility.',
  },

  // ==========================================
  // 4TH GRADE (Ages 9-10)
  // ==========================================
  {
    id: 'g4-1',
    gradeLevel: '4th_grade',
    subject: 'math',
    subjectLabel: 'Two-Dimensional Area',
    subjectIcon: '📐',
    question: 'A rectangular garden measures 9 feet in length and 7 feet in width. What is the total AREA of the garden in square feet?',
    options: ['32 sq ft', '54 sq ft', '63 sq ft', '72 sq ft'],
    correctAnswerIndex: 2,
    hint: 'Area of a rectangle is the product of its two adjacent dimensions: length multiplied by width.',
    thinkingAngle: 'Grid Modeling: Picture 9 rows of 7 square tiles laid flat across the garden floor.',
    funFactExplanation: 'Brilliant work! 9 × 7 = 63 square feet. The perimeter would be (9 + 7) × 2 = 32 ft, but area measures total square units covered!',
  },
  {
    id: 'g4-2',
    gradeLevel: '4th_grade',
    subject: 'science',
    subjectLabel: 'Geology & Volcanology',
    subjectIcon: '🌋',
    question: 'What do geoscientists call molten liquid rock while it is still trapped UNDERGROUND inside the Earth’s crust?',
    options: ['Lava', 'Magma', 'Obsidian', 'Basalt'],
    correctAnswerIndex: 1,
    hint: 'Molten rock changes its scientific name the moment it erupts through a volcanic vent onto Earth’s surface.',
    thinkingAngle: 'Boundary Classifications: Scientists frequently use distinct names for the exact same substance depending on whether it is contained or exposed.',
    funFactExplanation: 'Super smart! Deep underground it is called magma. Once it breaches the surface and flows down a volcano, it is officially classified as lava!',
  },
  {
    id: 'g4-3',
    gradeLevel: '4th_grade',
    subject: 'wordplay',
    subjectLabel: 'Literary Devices',
    subjectIcon: '⚡',
    question: 'In the sentence "The lightning danced playfully across the dark night sky", which figurative language device is used?',
    options: ['Hyperbole', 'Personification', 'Alliteration', 'Onomatopoeia'],
    correctAnswerIndex: 1,
    hint: 'Dancing is a human action. What device gives human actions or feelings to non-human things?',
    thinkingAngle: 'Device Deconstruction: Look at the verb ("danced") and examine what type of being typically performs that action.',
    funFactExplanation: 'Great literary analysis! Personification attributes human emotions or actions to inanimate objects or weather events to create vivid descriptions.',
  },
  {
    id: 'g4-4',
    gradeLevel: '4th_grade',
    subject: 'logic',
    subjectLabel: 'Wording Precision',
    subjectIcon: '🐑',
    question: 'A rancher had 17 sheep in a pasture. A sudden storm broke the fence, and all but 9 ran away. How many sheep does the rancher have left?',
    options: ['8 sheep', '9 sheep', '17 sheep', '0 sheep'],
    correctAnswerIndex: 1,
    hint: 'Read the phrase very carefully: "all BUT nine" ran away. Who remained?',
    thinkingAngle: 'Semantic Traps: Our brains often rush to subtract (17 - 9 = 8), but the word "but" directly states the remaining amount!',
    funFactExplanation: 'Classic logic trap avoided! "All but 9" means exactly 9 sheep stayed behind! Careful reading is a key skill in higher math and science.',
  },
  {
    id: 'g4-5',
    gradeLevel: '4th_grade',
    subject: 'nature',
    subjectLabel: 'Continental Geography',
    subjectIcon: '🗺️',
    question: 'Which river system is the longest on the North American continent, flowing from Montana down to the Gulf of Mexico?',
    options: ['Colorado River', 'Mississippi-Missouri River System', 'Hudson River', 'Rio Grande'],
    correctAnswerIndex: 1,
    hint: 'This river system flows through the heart of the United States and drains over 40% of the continental landmass.',
    thinkingAngle: 'System Combination: Geographers treat connected main stems and tributaries as a unified drainage system.',
    funFactExplanation: 'Terrific! The Missouri River flows 2,341 miles before merging with the Mississippi River, creating a combined navigation network over 3,700 miles long!',
  },
  {
    id: 'g4-6',
    gradeLevel: '4th_grade',
    subject: 'math',
    subjectLabel: 'Positional Place Value',
    subjectIcon: '🔢',
    question: 'In the number 48,251, what is the exact PLACE VALUE of the digit 8?',
    options: ['80', '800', '8,000 (Thousands)', '80,000 (Ten-Thousands)'],
    correctAnswerIndex: 2,
    hint: 'Count positions from right to left: ones (1), tens (5), hundreds (2), and then the thousands.',
    thinkingAngle: 'Base-10 Multipliers: Each step to the left increases value tenfold (10^0, 10^1, 10^2, 10^3).',
    funFactExplanation: 'Spot on! The digit 8 sits in the thousands column, representing 8 groups of 1,000 = 8,000!',
  },
  {
    id: 'g4-7',
    gradeLevel: '4th_grade',
    subject: 'logic',
    subjectLabel: 'Generational Logic',
    subjectIcon: '🎣',
    question: 'Two fathers and two sons go fishing on a lake. Each person catches exactly one trout, yet only 3 trout were caught in total. How is this possible?',
    options: ['One fish fell back in the lake', 'They are a Grandfather, a Father, and a Son', 'One person didn\'t count', 'A fish was split in half'],
    correctAnswerIndex: 1,
    hint: 'Think about multiple familial roles: can one person be both a son to someone and a father to someone else at the same time?',
    thinkingAngle: 'Overlapping Roles: A single human can fulfill multiple identity roles simultaneously within a three-generation lineage.',
    funFactExplanation: 'Ingenious! The grandfather is a father; the father is both a son and a father; and the youngest is a son! That makes 2 fathers and 2 sons among just 3 people!',
  },
  {
    id: 'g4-8',
    gradeLevel: '4th_grade',
    subject: 'math',
    subjectLabel: 'Prime Number Theory',
    subjectIcon: '🛡️',
    question: 'Which of the following numbers is a PRIME number (having only two distinct factors: 1 and itself)?',
    options: ['15', '17', '21', '27'],
    correctAnswerIndex: 1,
    hint: 'Test divisibility: 15 = 3 × 5; 21 = 3 × 7; 27 = 3 × 9. Which number cannot be divided evenly by any number other than 1 and itself?',
    thinkingAngle: 'Factor Elimination: Search for composite factors (2, 3, 5). If none exist below the square root, the integer is prime.',
    funFactExplanation: 'Outstanding! 17 is prime! Prime numbers are the "indivisible building blocks" of mathematics because every whole number can be factored into primes.',
  },
  {
    id: 'g4-9',
    gradeLevel: '4th_grade',
    subject: 'science',
    subjectLabel: 'Acoustic Physics',
    subjectIcon: '🔊',
    question: 'Sound waves travel through vibrations of matter. Why can sound NEVER travel through the empty vacuum of deep outer space?',
    options: ['Space is too cold', 'There are no air molecules or particles to vibrate and carry sound waves', 'The Sun absorbs all sound', 'Sound only travels on land'],
    correctAnswerIndex: 1,
    hint: 'Think about what a wave needs to travel: if you drop a pebble in an empty bucket with no water, can you make water ripples?',
    thinkingAngle: 'Mechanical vs Electromagnetic: Sound requires a physical medium to transmit compression waves, whereas light can travel through empty space.',
    funFactExplanation: 'Brilliant science! Because deep space is an almost perfect vacuum with virtually no particles, sound cannot travel! Sci-fi movies with booming space explosions are scientifically inaccurate!',
  },
  {
    id: 'g4-10',
    gradeLevel: '4th_grade',
    subject: 'riddle',
    subjectLabel: 'Travel Riddle',
    subjectIcon: '📮',
    question: 'What can travel around the entire world while staying tucked in the exact same corner?',
    options: ['A Compass', 'A Postage Stamp', 'A Suitcase', 'A Clock'],
    correctAnswerIndex: 1,
    hint: 'Think about letters and postcards sent across oceans to faraway countries.',
    thinkingAngle: 'Object on a Carrier: Focus on an item that is affixed to a corner of a moving vehicle or mailing envelope.',
    funFactExplanation: 'Spot on! A postage stamp stays in the top-right corner of an envelope as it flies across continents and oceans to deliver mail!',
  },
  {
    id: 'g4-11',
    gradeLevel: '4th_grade',
    subject: 'wordplay',
    subjectLabel: 'Idioms & Wisdom',
    subjectIcon: '🥚',
    question: 'When an elder advises "Don’t put all your eggs in one basket", what practical life advice are they giving?',
    options: ['Always buy fresh eggs at the market', 'Don’t risk everything on a single plan or idea', 'Eat breakfast every day', 'Carry heavy things carefully'],
    correctAnswerIndex: 1,
    hint: 'Think about what happens if someone trips while holding the only basket that contains every single egg they own.',
    thinkingAngle: 'Metaphorical Risk Diversification: The physical imagery warns against concentrating vulnerability in a single point of failure.',
    funFactExplanation: 'Terrific! This proverb encourages diversification—spreading your efforts or investments so that if one thing fails, you don’t lose everything!',
  },
  {
    id: 'g4-12',
    gradeLevel: '4th_grade',
    subject: 'science',
    subjectLabel: 'Orbital Mechanics',
    subjectIcon: '🌍',
    question: 'Why do we experience four distinct seasons (Spring, Summer, Fall, Winter) on Earth throughout the year?',
    options: ['Earth moves closer and further from the Sun', 'Earth’s axis is tilted at 23.5 degrees as it orbits the Sun', 'Clouds block the Sun in winter', 'The Sun gets colder in December'],
    correctAnswerIndex: 1,
    hint: 'Notice that when it is Winter in North America, it is Summer in Australia! If distance to the Sun were the cause, both would freeze together.',
    thinkingAngle: 'Challenging Common Misconceptions: Proximity to the sun does not cause seasons; the angle of solar incidence due to planetary tilt does.',
    funFactExplanation: 'Masterful astronomy! Earth’s 23.5° axial tilt causes hemispheres to lean toward the Sun (summer) or away from it (winter), concentrating or spreading out solar energy!',
  },

  // ==========================================
  // 5TH GRADE (Ages 10-11)
  // ==========================================
  {
    id: 'g5-1',
    gradeLevel: '5th_grade',
    subject: 'math',
    subjectLabel: 'Order of Operations',
    subjectIcon: '📊',
    question: 'Evaluate this mathematical expression using the standard Order of Operations (PEMDAS): 5 + 3 × (8 - 2)',
    options: ['48', '23', '30', '19'],
    correctAnswerIndex: 1,
    hint: 'Remember operational hierarchy: resolve grouped parentheses first, perform multiplication second, and conclude with addition.',
    thinkingAngle: 'Syntactic Grammar: Mathematics uses strict precedence rules to avoid ambiguity in multi-step equations.',
    funFactExplanation: 'Outstanding! (8 - 2) = 6; then 3 × 6 = 18; finally 5 + 18 = 23. Order of operations guarantees everyone in the world computes the exact same result!',
  },
  {
    id: 'g5-2',
    gradeLevel: '5th_grade',
    subject: 'science',
    subjectLabel: 'Mechanical Energy',
    subjectIcon: '🎢',
    question: 'When a roller coaster train reaches the apex of the highest hill and pauses for a split-second, what form of energy is maximized?',
    options: ['Kinetic Energy', 'Gravitational Potential Energy', 'Thermal Energy', 'Chemical Energy'],
    correctAnswerIndex: 1,
    hint: 'Think about "stored" energy waiting to be unleashed by height versus energy of active motion.',
    thinkingAngle: 'Conservation of Energy: As kinetic energy decreases climbing upward against gravity, it converts into stored potential energy.',
    funFactExplanation: 'Spot on! At the peak, potential energy is at its absolute maximum. As the coaster plunges down, gravity converts that potential energy into kinetic energy (speed)!',
  },
  {
    id: 'g5-3',
    gradeLevel: '5th_grade',
    subject: 'logic',
    subjectLabel: 'Relational Analogy',
    subjectIcon: '🐟',
    question: 'Complete the biological collective noun analogy: BIRD is to FLOCK as FISH is to ______?',
    options: ['HERD', 'PACK', 'SCHOOL', 'SWARM'],
    correctAnswerIndex: 2,
    hint: 'What specific term do marine biologists use for a synchronized group of swimming fish?',
    thinkingAngle: 'Category Mapping: Identify the specific relationship in the prompt pair (individual animal to its collective noun) and mirror it.',
    funFactExplanation: 'Exact! A group of fish swimming in coordination is called a school (or shoal)! Wolves form packs, cattle form herds, and bees form swarms.',
  },
  {
    id: 'g5-4',
    gradeLevel: '5th_grade',
    subject: 'riddle',
    subjectLabel: 'Wear & Tear Riddle',
    subjectIcon: '🕯️',
    question: 'I am tall when I am young, and I grow shorter the older I get. What am I?',
    options: ['A Tree', 'A Candle or Pencil', 'A Mountain', 'A Human Being'],
    correctAnswerIndex: 1,
    hint: 'Think about objects whose material is burned away or shaved down as they fulfill their purpose.',
    thinkingAngle: 'Inverted Growth: While living organisms grow taller over time, consumable tools diminish as they are utilized.',
    funFactExplanation: 'Genius! Both candles and pencils start tall and shrink shorter with every use! Lateral thinking embraces alternative timelines.',
  },
  {
    id: 'g5-5',
    gradeLevel: '5th_grade',
    subject: 'nature',
    subjectLabel: 'Cardiovascular Biology',
    subjectIcon: '🫀',
    question: 'Which muscular organ in the human body contracts about 100,000 times daily to pump blood through 60,000 miles of vessels?',
    options: ['The Brain', 'The Stomach', 'The Heart', 'The Liver'],
    correctAnswerIndex: 2,
    hint: 'Place your hand on the center-left of your chest: feel the rhythmic muscular pulse driving your circulation.',
    thinkingAngle: 'Organ Function: Differentiate between metabolic processing (liver), cognition (brain), digestion (stomach), and hemodynamic pumping.',
    funFactExplanation: 'Incredible! The human heart pumps about 2,000 gallons of blood every day! If stretched end-to-end, a single person’s blood vessels could circle Earth more than twice.',
  },
  {
    id: 'g5-6',
    gradeLevel: '5th_grade',
    subject: 'math',
    subjectLabel: 'Spatial Volume',
    subjectIcon: '📦',
    question: 'A rectangular container has dimensions of 5 inches long, 4 inches wide, and 3 inches high. What is its total VOLUME in cubic inches?',
    options: ['12 cu in', '45 cu in', '60 cu in', '80 cu in'],
    correctAnswerIndex: 2,
    hint: 'Volume is the product of all three 3D spatial dimensions: Length × Width × Height.',
    thinkingAngle: 'Layered Area: Calculate the base area first (5 × 4 = 20), then multiply by how many layers high it stacks (20 × 3).',
    funFactExplanation: 'Perfection! 5 × 4 = 20, and 20 × 3 = 60 cubic inches. Volume measures the capacity of 3D space enclosed by a boundary.',
  },
  {
    id: 'g5-7',
    gradeLevel: '5th_grade',
    subject: 'logic',
    subjectLabel: 'Monopoly Lateral Riddle',
    subjectIcon: '🎲',
    question: 'A man pushes his car up to a hotel and immediately shouts to the owner that he is completely bankrupt! What is happening?',
    options: ['He crashed into the building', 'He is playing the board game Monopoly', 'He ran out of gas on a mountain road', 'He got a hotel room bill'],
    correctAnswerIndex: 1,
    hint: 'Step out of the real-world road network and into a world of silver game tokens, dice, and colorful play money.',
    thinkingAngle: 'Domain Shift: When a scenario makes no physical or financial sense in reality, check if it obeys the rules of a simulation or game.',
    funFactExplanation: 'Brilliant lateral deduction! The player landed on a property with a hotel in the board game Monopoly! Puzzles like this teach us not to assume real-world physics when context is missing.',
  },
  {
    id: 'g5-8',
    gradeLevel: '5th_grade',
    subject: 'science',
    subjectLabel: 'Archimedes Buoyancy',
    subjectIcon: '🚢',
    question: 'A solid steel bolt sinks immediately in a bucket of water, yet an ocean freighter made of thousands of tons of steel floats easily. Why?',
    options: ['Ocean saltwater is made of oil', 'The ship\'s hollow hull displaces a weight of water equal to its own total weight', 'The ship’s engines lift it upward', 'Air inside the steel makes metal disappear'],
    correctAnswerIndex: 1,
    hint: 'Think about Archimedes’ principle: an object floats when its buoyant upward force (weight of displaced water) balances its downward gravitational weight.',
    thinkingAngle: 'Average Density vs Material Density: A hollow shape includes vast volumes of air, making the entire object’s average density less than water.',
    funFactExplanation: 'Phenomenal physics! Because a ship is mostly hollow air inside, its overall average density is lower than water. It pushes aside enough water to create a buoyant force equal to its massive weight!',
  },
  {
    id: 'g5-9',
    gradeLevel: '5th_grade',
    subject: 'math',
    subjectLabel: 'Gauss Summation Shortcut',
    subjectIcon: '➕',
    question: 'What is the sum of all consecutive whole numbers from 1 to 10 (1 + 2 + 3 + ... + 10)?',
    options: ['45', '50', '55', '60'],
    correctAnswerIndex: 2,
    hint: 'Pair the numbers from the outside edges inward: 1 + 10 = 11; 2 + 9 = 11; 3 + 8 = 11... How many pairs of 11 are there?',
    thinkingAngle: 'Symmetric Pairing: Instead of brute-force sequential adding, match complementary extremes to form equal constants.',
    funFactExplanation: 'Masterful! There are 5 pairs that each sum to 11 (5 × 11 = 55)! The legendary mathematician Carl Friedrich Gauss discovered this method as a young student in elementary school.',
  },
  {
    id: 'g5-10',
    gradeLevel: '5th_grade',
    subject: 'riddle',
    subjectLabel: 'Keyboard Riddle',
    subjectIcon: '⌨️',
    question: 'I have keys that open no locks, space with no rooms, and you can enter but you cannot go outside. What am I?',
    options: ['A Piano', 'A Computer Keyboard', 'A Jailhouse', 'A Mystery Map'],
    correctAnswerIndex: 1,
    hint: 'Look down at your desk or laptop: what are you typing on right now?',
    thinkingAngle: 'Homonym Puns: Words like "keys", "space", and "enter" have technical definitions in computing distinct from architectural meanings.',
    funFactExplanation: 'Sharp thinking! A computer keyboard has letter keys, a Space bar, and an Enter key! Language puzzles highlight how words adapt to new technology.',
  },
  {
    id: 'g5-11',
    gradeLevel: '5th_grade',
    subject: 'science',
    subjectLabel: 'Chemical Reactions',
    subjectIcon: '🧪',
    question: 'When an iron nail is left outdoors in damp air and slowly turns into reddish-brown crumbly rust, what chemical reaction is occurring?',
    options: ['Sublimation', 'Oxidation (Iron combining with Oxygen)', 'Photosynthesis', 'Nuclear Fission'],
    correctAnswerIndex: 1,
    hint: 'Look at the chemical partners: iron atoms are bonding with oxygen gas and moisture in the atmosphere.',
    thinkingAngle: 'Chemical vs Physical Change: Rusting produces an entirely new chemical compound (iron oxide) with different properties than metallic iron.',
    funFactExplanation: 'Spot on! Rust is iron oxide (Fe2O3). It is an oxidation reaction where oxygen atoms bond with iron. Rust takes up more space than iron, causing it to flake and weaken metal structures!',
  },
  {
    id: 'g5-12',
    gradeLevel: '5th_grade',
    subject: 'wordplay',
    subjectLabel: 'Oxymoron Paradoxes',
    subjectIcon: '🤫',
    question: 'Which of the following literary phrases is an OXYMORON—combining two terms that appear directly contradictory?',
    options: ['Dark night', 'Deafening silence', 'Running quickly', 'Freezing blizzard'],
    correctAnswerIndex: 1,
    hint: 'Can literal silence be deafening? Look for two opposite ideas juxtaposed together.',
    thinkingAngle: 'Paradoxical Pairing: An oxymoron creates emphasis by locking two antithetical concepts into a single descriptive phrase.',
    funFactExplanation: 'Brilliant! "Deafening silence" is a classic oxymoron! Other famous oxymorons include "jumbo shrimp", "bittersweet", and "seriously funny".',
  },

  // ==========================================
  // MIDDLE SCHOOL (6th-8th Grade / Ages 11-14)
  // ==========================================
  {
    id: 'ms-1',
    gradeLevel: 'middle_school',
    subject: 'math',
    subjectLabel: 'Algebraic Equilibrium',
    subjectIcon: '⚖️',
    question: 'Solve for the unknown variable x in the linear equation: 3x + 7 = 28. What is x?',
    options: ['x = 5', 'x = 7', 'x = 9', 'x = 21'],
    correctAnswerIndex: 1,
    hint: 'Treat the equation as a balance scale: first remove the constant term (7) from both sides, then isolate x by dividing by its coefficient.',
    thinkingAngle: 'Inverse Operations: Undo operations in reverse order of evaluation (subtract the added constant, then divide by the multiplier).',
    funFactExplanation: 'Awesome algebra! 28 - 7 = 21, and 21 ÷ 3 = 7. The word "Algebra" comes from the 9th-century Arabic treatise "Al-Jabr", meaning "reunion of broken parts"!',
  },
  {
    id: 'ms-2',
    gradeLevel: 'middle_school',
    subject: 'science',
    subjectLabel: 'Atmospheric Chemistry',
    subjectIcon: '💨',
    question: 'What single gas makes up approximately 78% of Earth’s atmosphere by volume?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
    correctAnswerIndex: 2,
    hint: 'Most people instinctively guess oxygen, but oxygen only accounts for ~21%. Think about the stable, unreactive gas that buffers our air.',
    thinkingAngle: 'Intuition vs Empirical Data: The gas most critical for immediate respiration is not necessarily the most abundant volume component.',
    funFactExplanation: 'Fascinating science! Earth’s atmosphere is ~78% Nitrogen, ~21% Oxygen, and ~0.9% Argon. Nitrogen’s triple bond makes it stable, preventing runaway fires on our planet!',
  },
  {
    id: 'ms-3',
    gradeLevel: 'middle_school',
    subject: 'logic',
    subjectLabel: 'Rate & Work Deduction',
    subjectIcon: '⌨️',
    question: 'If two typists can type two pages in two minutes, how many typists would be needed to type 18 pages in six minutes?',
    options: ['3 typists', '6 typists', '9 typists', '12 typists'],
    correctAnswerIndex: 1,
    hint: 'Deconstruct to unit rates: how many pages does a single typist produce in one single minute?',
    thinkingAngle: 'Unit Rate Normalization: Reduce the multi-variable problem to (work) / (worker × time) before scaling to the new conditions.',
    funFactExplanation: 'Brilliant deduction! Two typists do 2 pages in 2 minutes = 1 page per minute total, so 1 typist types 0.5 pages/min. In 6 minutes, 1 typist types 3 pages. To get 18 pages: 18 ÷ 3 = 6 typists!',
  },
  {
    id: 'ms-4',
    gradeLevel: 'middle_school',
    subject: 'nature',
    subjectLabel: 'Molecular Genetics',
    subjectIcon: '🧬',
    question: 'What is the double-helix macromolecule that stores the hereditary genetic instructions for all known living organisms?',
    options: ['RNA', 'DNA (Deoxyribonucleic Acid)', 'ATP', 'Glucose'],
    correctAnswerIndex: 1,
    hint: 'Think of the twisted ladder structure resolved in 1953 with key data from Rosalind Franklin’s X-ray crystallography.',
    thinkingAngle: 'Molecular Specificity: Differentiate between energy storage (ATP), short-term messengers (RNA), and master chromosomal archives.',
    funFactExplanation: 'Spot on! DNA contains the biological code of life. If you unraveled and linked the DNA from all cells in your body, it would stretch from Earth to Pluto and back multiple times!',
  },
  {
    id: 'ms-5',
    gradeLevel: 'middle_school',
    subject: 'riddle',
    subjectLabel: 'Hydrodynamic Tide Paradox',
    subjectIcon: '⛵',
    question: 'A boat floats in a harbor with a rope ladder hanging over its side into the ocean. The rungs are 12 inches apart. If the incoming ocean tide rises by 4 feet, how many ladder rungs will submerge underwater?',
    options: ['4 rungs', '8 rungs', 'None (0 rungs)', '2 rungs'],
    correctAnswerIndex: 2,
    hint: 'Think about physics: what happens to a floating vessel when the water level beneath it rises?',
    thinkingAngle: 'Relative Frame of Reference: The ladder is attached to the boat, not to the seabed. When the water rises, the buoyant reference frame moves with it!',
    funFactExplanation: 'Gotcha! The boat floats! As the tide rises 4 feet, the boat and its ladder rise exactly 4 feet with the water level, so no additional rungs submerge!',
  },
  {
    id: 'ms-6',
    gradeLevel: 'middle_school',
    subject: 'science',
    subjectLabel: 'Cosmic Speed of Light',
    subjectIcon: '⚡',
    question: 'Light emitted from the surface of the Sun travels across 93 million miles of vacuum to reach Earth. Approximately how long does this journey take?',
    options: ['Instantaneous (0 seconds)', 'About 8 minutes and 20 seconds', '1 full hour', '24 hours'],
    correctAnswerIndex: 1,
    hint: 'Light travels at ~186,282 miles per second. Divide 93,000,000 miles by the speed of light to determine the transit time in seconds (~500 seconds).',
    thinkingAngle: 'Finite Velocity in Scale: Nothing travels faster than light in a vacuum, but cosmic distances are so vast that light still takes minutes or hours to cross planetary orbits.',
    funFactExplanation: 'Mind-blowing physics! Sunlight takes approximately 500 seconds (8 min 20 sec) to arrive. When you look at the daytime sky, you are seeing what the Sun looked like over 8 minutes ago!',
  },
  {
    id: 'ms-7',
    gradeLevel: 'middle_school',
    subject: 'logic',
    subjectLabel: 'Sequence of Operations',
    subjectIcon: '🪵',
    question: 'You enter a freezing, pitch-black mountain cabin with only ONE match. Inside the cabin are an oil lamp, a wood fireplace, and a candle. What do you light FIRST?',
    options: ['The Oil Lamp', 'The Fireplace', 'The Candle', 'The Match'],
    correctAnswerIndex: 3,
    hint: 'Think chronologically: before you can ignite ANY of the heat sources in the room, what must be burning in your hand?',
    thinkingAngle: 'Prerequisite Analysis: Identify the unmentioned foundational action that enables all subsequent options.',
    funFactExplanation: 'Classic lateral thinking! You must light the match first! Without lighting the match, none of the other items can ever be lit. Lateral thinkers inspect prerequisite assumptions.',
  },
  {
    id: 'ms-8',
    gradeLevel: 'middle_school',
    subject: 'math',
    subjectLabel: 'Euclidean Geometry',
    subjectIcon: '📐',
    question: 'On a flat two-dimensional plane, what is the exact sum of the interior angles of ANY triangle?',
    options: ['90 degrees', '180 degrees', '270 degrees', '360 degrees'],
    correctAnswerIndex: 1,
    hint: 'If you tear the three corner angles off any paper triangle and place their vertices together side by side, they form a perfectly straight line.',
    thinkingAngle: 'Geometric Invariance: Regardless of whether a triangle is acute, obtuse, or scalene, its internal angular budget is fixed in Euclidean space.',
    funFactExplanation: 'Spot on! The interior angles of any planar triangle always sum to 180°. On curved non-Euclidean surfaces (like a globe), angles can actually exceed 180°!',
  },
  {
    id: 'ms-9',
    gradeLevel: 'middle_school',
    subject: 'science',
    subjectLabel: 'Newtonian Inertia',
    subjectIcon: '🚀',
    question: 'Newton’s First Law of Motion states that an object at rest remains at rest unless acted on by an unbalanced force. What is this intrinsic resistance to changes in motion called?',
    options: ['Momentum', 'Inertia', 'Friction', 'Velocity'],
    correctAnswerIndex: 1,
    hint: 'This property depends directly on an object’s mass: it explains why pushing a stalled car is vastly harder than pushing a shopping cart.',
    thinkingAngle: 'Fundamental Physical Definitions: Distinguish between the tendency to resist acceleration (inertia) versus the product of mass and velocity (momentum).',
    funFactExplanation: 'Masterful! Inertia is an object’s resistance to any change in its velocity. It is why seatbelts are essential—when a car brakes abruptly, your body’s inertia keeps moving forward!',
  },
  {
    id: 'ms-10',
    gradeLevel: 'middle_school',
    subject: 'riddle',
    subjectLabel: 'Discovery vs Existence',
    subjectIcon: '🏔️',
    question: 'Before Mount Everest was surveyed, measured, and named by British geographers in 1856, what was the tallest mountain on Earth?',
    options: ['K2', 'Mount Kilimanjaro', 'Mount Everest', 'Denali'],
    correctAnswerIndex: 2,
    hint: 'Don’t confuse human awareness with physical reality: did the mountain suddenly grow taller because humans mapped it?',
    thinkingAngle: 'Ontological Independence: Physical geography exists independently of human observation, cataloging, or naming.',
    funFactExplanation: 'Outstanding! Mount Everest was still the tallest mountain on Earth—it just hadn’t been named or surveyed by modern cartographers yet!',
  },
  {
    id: 'ms-11',
    gradeLevel: 'middle_school',
    subject: 'math',
    subjectLabel: 'Discrete Probability',
    subjectIcon: '🎲',
    question: 'When rolling a single fair standard 6-sided die (numbers 1 to 6), what is the exact theoretical probability of rolling a PRIME number?',
    options: ['1/6', '2/6 (1/3)', '3/6 (1/2)', '4/6 (2/3)'],
    correctAnswerIndex: 2,
    hint: 'List all outcomes: 1, 2, 3, 4, 5, 6. Which ones are prime? Remember that 1 is NEITHER prime nor composite!',
    thinkingAngle: 'Sample Space Filtering: Count favorable events over total possible outcomes. Remember the strict definition of primes (exactly two distinct positive divisors).',
    funFactExplanation: 'Brilliant probability! The prime numbers on a die are 2, 3, and 5 (three outcomes). 3 out of 6 possibilities = 3/6 = 1/2 (50% chance)! Remember that 1 is not prime.',
  },
  {
    id: 'ms-12',
    gradeLevel: 'middle_school',
    subject: 'science',
    subjectLabel: 'Tectonic Dynamics',
    subjectIcon: '🌋',
    question: 'What comprehensive geological theory explains how massive lithospheric plates glide across the asthenosphere, causing earthquakes, volcanoes, and mountain building?',
    options: ['Continental Expansion', 'Plate Tectonics', 'Magnetic Pole Reversal', 'Gravitational Compression'],
    correctAnswerIndex: 1,
    hint: 'Think of Earth’s brittle outer shell being broken into giant puzzle pieces that drift over convection currents in the mantle.',
    thinkingAngle: 'Unified Geodynamic Framework: This theory unified Alfred Wegener’s continental drift with seafloor spreading discoveries.',
    funFactExplanation: 'Terrific! Plate Tectonics explains how continents collide to push up the Himalayas, pull apart to form the Atlantic Ocean, and grind together along the San Andreas Fault!',
  },
  {
    id: 'ms-13',
    gradeLevel: 'middle_school',
    subject: 'wordplay',
    subjectLabel: 'Anagram Scramble',
    subjectIcon: '🔤',
    question: 'What linguistic term describes a word or phrase formed by rearranging the exact letters of another word, such as transforming "LISTEN" into "SILENT"?',
    options: ['Palindrome', 'Anagram', 'Homonym', 'Acronym'],
    correctAnswerIndex: 1,
    hint: 'While a palindrome reads backwards, this wordplay involves shuffling the same pool of letters into an entirely different valid word.',
    thinkingAngle: 'Combinatorial Linguistics: Permuting characters without replacement creates an anagrammatic relationship.',
    funFactExplanation: 'Super job! An anagram rearranges letters to produce new words! For example: "ASTRONOMER" can be anagrammed into "MOON STARER"!',
  },
  {
    id: 'ms-14',
    gradeLevel: 'middle_school',
    subject: 'logic',
    subjectLabel: 'Constraint Elimination',
    subjectIcon: '📦',
    question: 'You have three boxes: one has only Apples, one has only Oranges, and one has both Apples & Oranges mixed. ALL THREE BOXES ARE LABELED INCORRECTLY. You may draw just ONE fruit from ONE box without looking inside. Which box must you pick from to correctly identify all three?',
    options: ['The "Apples" box', 'The "Oranges" box', 'The "Apples & Oranges" box', 'It is impossible with one pick'],
    correctAnswerIndex: 2,
    hint: 'Leverage the absolute constraint: EVERY label is wrong! If you pull a single fruit from the "Apples & Oranges" box, what MUST that entire box be?',
    thinkingAngle: 'Maximizing Information from Negative Constraints: Since the mixed label cannot be mixed, a single sample definitively identifies that box, collapsing the remaining two via elimination!',
    funFactExplanation: 'Masterful logic! Since the "Apples & Oranges" box is mislabeled, it cannot be mixed! If you pull an apple, it is 100% the Apples box. The box labeled "Oranges" must then be the Mixed box, and the box labeled "Apples" must be Oranges!',
  },

  // ==========================================
  // HIGH SCHOOL (9th-12th Grade / Ages 14-18)
  // ==========================================
  {
    id: 'hs-1',
    gradeLevel: 'high_school',
    subject: 'math',
    subjectLabel: 'Pythagorean Triples',
    subjectIcon: '📐',
    question: 'A right-angled triangle has orthogonal leg lengths of a = 6 and b = 8. What is the length of the hypotenuse c?',
    options: ['c = 9', 'c = 10', 'c = 12', 'c = 14'],
    correctAnswerIndex: 1,
    hint: 'Look for proportional scaling of the fundamental integer triple (3, 4, 5). Both legs here are doubled.',
    thinkingAngle: 'Geometric Similitude: Scaling right triangles by a constant factor k scales all three sides by k (2 × [3, 4, 5] = [6, 8, 10]).',
    funFactExplanation: 'Masterful! By the Pythagorean theorem: a² + b² = c² -> 36 + 64 = 100 -> √100 = 10. Recognizing primitive triples (3-4-5, 5-12-13) saves crucial time on standardized exams!',
  },
  {
    id: 'hs-2',
    gradeLevel: 'high_school',
    subject: 'science',
    subjectLabel: 'Subatomic Particle Physics',
    subjectIcon: '⚛️',
    question: 'Which fundamental subatomic lepton orbits outside the atomic nucleus, carries a negative elementary charge (-1e), and mediates chemical bonding?',
    options: ['Proton', 'Neutron', 'Electron', 'Positron'],
    correctAnswerIndex: 2,
    hint: 'Protons carry positive charge inside the nucleus, neutrons are neutral, and these low-mass particles form probability clouds in outer orbitals.',
    thinkingAngle: 'Standard Model Categorization: Differentiate composite baryons (protons, neutrons made of quarks) from fundamental leptons.',
    funFactExplanation: 'Spot on! Electrons possess an invariant charge of -1.602 × 10^-19 Coulombs and have roughly 1/1,836th the mass of a proton. Their quantum exchange drives all chemical bonding and electrical circuitry!',
  },
  {
    id: 'hs-3',
    gradeLevel: 'high_school',
    subject: 'logic',
    subjectLabel: 'Conditional Probability (Monty Hall)',
    subjectIcon: '🚪',
    question: 'In the Monty Hall Problem (3 doors: 1 sports car, 2 goats), you pick Door 1. The host, who knows what is behind every door, opens Door 3 to reveal a goat. He offers you the option to switch to Door 2. What are your mathematical odds of winning the car if you SWITCH?',
    options: ['1/3 (33.3%)', '1/2 (50.0%)', '2/3 (66.7%)', '3/4 (75.0%)'],
    correctAnswerIndex: 2,
    hint: 'Examine initial state probability: your first pick had a 1/3 chance of being correct and a 2/3 chance of being wrong. Where does that 2/3 probability go when Monty eliminates a goat?',
    thinkingAngle: 'Asymmetric Information Release: The host’s action is not random—he must intentionally avoid the car, which concentrates the 2/3 probability onto the remaining unselected door!',
    funFactExplanation: 'Counterintuitive genius! Switching doubles your odds to 2/3! Your initial door had only a 1/3 chance of being right. Because Monty always reveals a goat, the unchosen remaining door inherits the entire 2/3 complement probability!',
  },
  {
    id: 'hs-4',
    gradeLevel: 'high_school',
    subject: 'nature',
    subjectLabel: 'Cellular Bioenergetics',
    subjectIcon: '🔋',
    question: 'Which double-membraned eukaryotic organelle contains its own circular mtDNA and conducts the Krebs cycle and oxidative phosphorylation to synthesize ATP?',
    options: ['Ribosome', 'Mitochondria', 'Golgi Apparatus', 'Endoplasmic Reticulum'],
    correctAnswerIndex: 1,
    hint: 'This organelle originated via endosymbiosis over a billion years ago and serves as the metabolic power generator of eukaryotic cells.',
    thinkingAngle: 'Endosymbiotic Theory: Look for the organelle with independent binary fission, double membranes, and distinct bacterial-like circular DNA.',
    funFactExplanation: 'Classic biology! Mitochondria generate Adenosine Triphosphate (ATP) through aerobic cellular respiration. Mitochondrial DNA is passed down almost exclusively along maternal lineages!',
  },
  {
    id: 'hs-5',
    gradeLevel: 'high_school',
    subject: 'wordplay',
    subjectLabel: 'Rhetorical Fallacies',
    subjectIcon: '🏛️',
    question: 'What logical fallacy occurs when a speaker bypasses the empirical merits of an opponent’s argument and attacks their personal character or background instead?',
    options: ['Straw Man', 'Ad Hominem', 'Slippery Slope', 'False Dilemma'],
    correctAnswerIndex: 1,
    hint: 'The Latin term translates literally to "against the person" or "to the man".',
    thinkingAngle: 'Argument Validity vs Source Bias: A claim’s logical soundness depends on empirical evidence and internal consistency, not the pedigree or character of who states it.',
    funFactExplanation: 'Sharp rhetorical analysis! An "Ad Hominem" fallacy substitutes personal insults or character attacks for substantive counter-evidence. Identifying fallacies is essential for critical thinking and debate!',
  },
  {
    id: 'hs-6',
    gradeLevel: 'high_school',
    subject: 'math',
    subjectLabel: 'Permutations & Factorials',
    subjectIcon: '🔢',
    question: 'In a 100-meter sprint final featuring 4 runners, how many distinct permutations exist for awarding 1st, 2nd, 3rd, and 4th place (calculated as 4 factorial, or 4!)?',
    options: ['12 ways', '16 ways', '24 ways', '32 ways'],
    correctAnswerIndex: 2,
    hint: 'Apply the Fundamental Counting Principle: you have 4 choices for 1st place; once chosen, 3 remain for 2nd; then 2 for 3rd; and 1 for 4th. Multiply them together.',
    thinkingAngle: 'Sequential Independent Reductions: Each selection without replacement reduces the remaining decision tree by one branch (n × (n-1) × ... × 1).',
    funFactExplanation: 'Spot on! 4 × 3 × 2 × 1 = 24 unique finishing orders. Factorials grow at an astronomical rate—just 10 runners (10!) yields over 3.6 million possible orderings!',
  },
  {
    id: 'hs-7',
    gradeLevel: 'high_school',
    subject: 'logic',
    subjectLabel: 'Heuristic Assumption Audit',
    subjectIcon: '🏥',
    question: 'A father and son are in a severe motor accident. The father passes away at the scene. The son is rushed into emergency surgery. The chief surgeon enters the operating room, looks at the boy, and pales: "I cannot operate on this patient; he is my son!" How is this possible?',
    options: ['The surgeon is lying', 'The surgeon is the boy\'s mother', 'The boy has two adoptive fathers', 'Both B and C are valid logical explanations'],
    correctAnswerIndex: 3,
    hint: 'Examine any unconscious assumptions about who can hold the title of chief surgeon or family composition.',
    thinkingAngle: 'Cognitive Bias Deconstruction: Lateral thinking requires recognizing cognitive schema traps where default gender or traditional assumptions blind logic.',
    funFactExplanation: 'Brilliant modern deduction! The surgeon could easily be his mother, or the boy could have two fathers! This famous puzzle was originally written to expose cognitive gender biases in professional roles.',
  },
  {
    id: 'hs-8',
    gradeLevel: 'high_school',
    subject: 'science',
    subjectLabel: 'Hydrogen Bonding Anomalies',
    subjectIcon: '❄️',
    question: 'Virtually all chemical compounds contract and become denser in their solid state than in their liquid state. Why does solid water (ice) do the exact opposite and FLOAT on liquid water?',
    options: ['Air bubbles get trapped in all ice', 'Hydrogen bonding locks water molecules into an open hexagonal crystalline lattice with greater empty volume', 'Cold temperatures destroy oxygen atoms', 'Surface tension repels ice cubes upward'],
    correctAnswerIndex: 1,
    hint: 'Think about molecular geometry: as thermal kinetic energy slows down near 0°C, how do hydrogen bonds orient the polar H2O molecules?',
    thinkingAngle: 'Intermolecular Forces & Packing Geometry: Open crystalline lattices increase molar volume, reducing density below that of disordered liquid states.',
    funFactExplanation: 'Profound chemistry! Water’s maximum density occurs at 3.98°C. As it freezes, hydrogen bonds force molecules into an open hexagonal lattice ~9% less dense than liquid water! Without this, lakes would freeze solid from the bottom up, extinguishing aquatic life!',
  },
  {
    id: 'hs-9',
    gradeLevel: 'high_school',
    subject: 'math',
    subjectLabel: 'Differential Growth Functions',
    subjectIcon: '📈',
    question: 'A petri dish colony of bacteria doubles its population every 20 minutes. What mathematical category of function governs this growth rate?',
    options: ['Linear Function', 'Polynomial Function', 'Exponential Function', 'Logarithmic Function'],
    correctAnswerIndex: 2,
    hint: 'Notice that the rate of change is proportional to the current population size itself (f(x) = a · b^x), rather than increasing by a fixed constant amount.',
    thinkingAngle: 'Proportional Rate of Change: When the derivative of a function is proportional to the function itself (dy/dt = ky), growth is exponential.',
    funFactExplanation: 'Exact! Exponential growth occurs when growth rate is proportional to instantaneous quantity. Unchecked, a single bacterium dividing every 20 minutes would theoretically outweigh planet Earth in less than two days!',
  },
  {
    id: 'hs-10',
    gradeLevel: 'high_school',
    subject: 'logic',
    subjectLabel: 'Game Theory Equilibrium',
    subjectIcon: '🤝',
    question: 'In the classic game theory formulation of the Prisoner’s Dilemma, when both players act strictly in their own individual rational self-interest without binding communication, what strategic outcome is reached?',
    options: ['Both cooperate (optimal joint reward)', 'Both defect / betray (Nash Equilibrium with sub-optimal outcome for both)', 'One cooperates and one defects', 'They randomly alternate choices'],
    correctAnswerIndex: 1,
    hint: 'Analyze the incentive matrix: for either prisoner, betraying yields a better individual payoff regardless of what the partner chooses, trapping both.',
    thinkingAngle: 'Nash Equilibrium vs Pareto Optimality: Individual rationality can lead to a stable equilibrium that is socially inferior to mutual trust.',
    funFactExplanation: 'Brilliant game theory! The Nash Equilibrium occurs where both defect, even though mutual cooperation yields a far superior collective sentence! This paradox explains real-world arms races, climate treaties, and price wars.',
  },
  {
    id: 'hs-11',
    gradeLevel: 'high_school',
    subject: 'science',
    subjectLabel: 'Optics & Snell’s Law',
    subjectIcon: '🌈',
    question: 'When a beam of white sunlight enters a triangular glass prism, it disperses into a rainbow spectrum. Why does violet light bend (refract) more sharply than red light?',
    options: ['Violet light has a shorter wavelength and slows down more in glass, giving it a higher refractive index', 'Violet light is heavier than red light', 'Glass contains purple dyes', 'Red light travels backwards inside glass'],
    correctAnswerIndex: 0,
    hint: 'Think about wave properties: wavelength and frequency dictate phase velocity through dense optical media. Shorter wavelengths interact more with electrons in the glass.',
    thinkingAngle: 'Chromatic Dispersion: Snell’s law index of refraction (n) is not constant across the electromagnetic spectrum; it is wavelength-dependent.',
    funFactExplanation: 'Spectacular optical physics! In glass, higher-frequency, shorter-wavelength violet light travels slower than longer-wavelength red light. This differential deceleration causes violet light to bend at a steeper angle!',
  },
  {
    id: 'hs-12',
    gradeLevel: 'high_school',
    subject: 'riddle',
    subjectLabel: 'Modular Measurement Puzzle',
    subjectIcon: '🪣',
    question: 'You have an unmarked 5-gallon jug, an unmarked 3-gallon jug, and an unlimited water source. How can you measure out EXACTLY 4 gallons of water using the least operations?',
    options: ['Fill the 3-gallon jug halfway', 'Fill the 5-gal jug, pour into 3-gal leaving 2; empty 3-gal; pour the 2 into 3-gal; fill 5-gal; top off 3-gal (taking 1 gal), leaving 4 gal!', 'Estimate using the height of the jug', 'It is mathematically impossible with odd numbers'],
    correctAnswerIndex: 1,
    hint: 'Think in terms of integer remainders (modular arithmetic): 5 - 3 = 2. If you transfer that 2 gallons into the 3-gallon jug, how much empty space remains for the next pour?',
    thinkingAngle: 'Linear Diophantine Equations: Any integer volume gcd(a, b) can be measured. Here, 5x + 3y = 4 has integer solutions (5(2) - 3(2) = 4)!',
    funFactExplanation: 'Masterful problem solving! By using the differential space (5 - 3 = 2) and transferring it, you leave exactly 1 gallon of space in the 3-gallon container, allowing you to siphon off exactly 1 gallon from a full 5-gallon jug!',
  },
  {
    id: 'hs-13',
    gradeLevel: 'high_school',
    subject: 'wordplay',
    subjectLabel: 'Philosophical Paradoxes',
    subjectIcon: '🌀',
    question: 'What term describes an apparently self-contradictory statement that, upon closer analytical scrutiny, reveals a profound, consistent underlying truth (e.g., "The only constant in life is change")?',
    options: ['A Tautology', 'A Paradox', 'A Non Sequitur', 'A Euphemism'],
    correctAnswerIndex: 1,
    hint: 'It sounds impossible or contradictory at first glance, but encapsulates a deeper reality.',
    thinkingAngle: 'Dialectical Synthesis: Examine statements where thesis and antithesis combine to expose a higher-order principle.',
    funFactExplanation: 'Superb! A paradox presents an apparent contradiction that challenges superficial intuition. Famous paradoxes in philosophy and physics (Zeno’s paradox, Fermi paradox) drive deep scientific breakthroughs!',
  },
  {
    id: 'hs-14',
    gradeLevel: 'high_school',
    subject: 'nature',
    subjectLabel: 'Mendelian Genetics',
    subjectIcon: '🧬',
    question: 'If two parent organisms are both heterozygous carriers (genotype Bb) for a recessive autosomal trait (b), what is the statistical probability that their offspring will express the recessive phenotype (genotype bb)?',
    options: ['0% (0 in 4)', '25% (1 in 4)', '50% (2 in 4)', '75% (3 in 4)'],
    correctAnswerIndex: 1,
    hint: 'Draw a 2 × 2 Punnett square crossing B and b with B and b. Out of the 4 quadrant combinations (BB, Bb, Bb, bb), how many inherit homozygous recessive alleles?',
    thinkingAngle: 'Independent Assortment Matrix: Each gamete inherits one allele with p = 0.5. By multiplication rule of independent probabilities: 0.5 × 0.5 = 0.25.',
    funFactExplanation: 'Outstanding genetics! Crossing Bb × Bb produces 1 BB : 2 Bb : 1 bb (a 1:2:1 genotypic ratio and 3:1 phenotypic ratio). The homozygous recessive condition (bb) has exactly a 25% (1 in 4) probability!',
  },
];
